- name: install nodejs:20
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: add app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download nd extract the file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: copy user service file
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: enable nd restart the service
  ansible.builtin.systemd_service:
    state: restarted
    name: user
    enabled: true
    daemon_reload: true